import type { NextPage } from 'next'
import Head from 'next/head'
import CTA from './cta/cta'
import Hero from './hero/hero'
import Team from './team/team'

const Home: NextPage = () => {
  return (
    <div className="relative bg-gray-800 overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero></Hero>
      <CTA></CTA>
      <Team></Team>

    </div>
  )
}

export default Home
