import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import CTA from './cta/cta'
import Hero from './hero/hero'
import Footer from './footer/footer'


const Home: NextPage = () => {
  return (
    <div className="relative bg-red-100 overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero></Hero>
      <CTA></CTA>
      <Footer></Footer>

    </div>
  )
}

export default Home
